---
name: Upload Artifacts

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload_artifacts:
    runs-on: ${{ matrix.runner_machine }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-intel-silicon, macos-latest]
        include: # See: https://docs.github.com/ja/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#using-environment-variables-in-a-matrix
          - os: ubuntu-latest
            runner_machine: ubuntu-latest
            edax_runner_bin_name: edax_runner
            libedax_shared_library_name: libedax.so
          - os: windows-latest
            runner_machine: windows-latest
            edax_runner_bin_name: edax_runner.exe
            libedax_shared_library_name: libedax-x64.dll
          - os: macos-intel-silicon
            # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
            runner_machine: macos-13
            edax_runner_bin_name: edax_runner
            libedax_shared_library_name: libedax.universal.dylib
          - os: macos-latest # apple silicon
            # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
            runner_machine: macos-latest
            edax_runner_bin_name: edax_runner
            libedax_shared_library_name: libedax.universal.dylib

    steps:
      - uses: actions/checkout@v5
      - uses: dart-lang/setup-dart@v1
      - name: install dependencies
        run: dart pub get

      - name: build edax_runner
        shell: bash
        run: ./scripts/build_edax_runner.sh ${{ matrix.edax_runner_bin_name }} ${{ matrix.libedax_shared_library_name }}

      - name: output build info
        shell: bash
        run: .github/scripts/output_build_info.sh build

      # See: https://github.com/actions/upload-artifact/issues/38
      # Workaround: https://github.com/actions/upload-artifact#maintaining-file-permissions-and-case-sensitive-files
      - name: tar files
        run: tar -cvf ${{ runner.os }}.tar build

      - uses: actions/upload-artifact@v4
        with:
          name: edax_runner-artifacts ${{ matrix.os }}
          path: build
